import type { User } from '../../domain/auth/types';
import { ROLE_PERMISSIONS } from '../../domain/auth/types';
import type { Laboratory } from '../../domain/laboratories/types';
import type { Equipment } from '../../domain/equipment/types';
import type { Reservation, WaitlistEntry } from '../../domain/reservations/types';
import type { CustodyRecord } from '../../domain/custody/types';
import type { MaintenanceOrder } from '../../domain/maintenance/types';
import type { Notification, SimulatedEmailLog } from '../../domain/notifications/types';
import type { AuditLogEntry } from '../../domain/audit/types';

export const SEED_USERS: User[] = [
  {
    id: 'usr-admin-01',
    name: 'Dr. Marcelo Valença (Administrador)',
    email: 'marcelo.valenca@instituto.edu.br',
    role: 'admin',
    title: 'Coordenador Geral de Laboratórios',
    department: 'Diretoria de Tecnologia & Pesquisa',
    matricula: 'COORD-9821',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    permissions: ROLE_PERMISSIONS.admin,
  },
  {
    id: 'usr-teach-01',
    name: 'Prof. Roberto Alencar (Professor 1)',
    email: 'roberto.alencar@instituto.edu.br',
    role: 'teacher',
    title: 'Docente em Redes e Sistemas Distribuídos',
    department: 'Departamento de Computação',
    matricula: 'PROF-1109',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    permissions: ROLE_PERMISSIONS.teacher,
  },
  {
    id: 'usr-teach-02',
    name: 'Profa. Carla Dias (Professor 2)',
    email: 'carla.dias@instituto.edu.br',
    role: 'teacher',
    title: 'Docente em Robótica & Inteligência Artificial',
    department: 'Departamento de Automação',
    matricula: 'PROF-2210',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    permissions: ROLE_PERMISSIONS.teacher,
  },
  {
    id: 'usr-tech-01',
    name: 'Ana Silva Santos (Técnica)',
    email: 'ana.silva@instituto.edu.br',
    role: 'technician',
    title: 'Técnica de Suporte e Manutenção',
    department: 'Gerência de Laboratórios de TI',
    matricula: 'TEC-4402',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    permissions: ROLE_PERMISSIONS.technician,
  },
  {
    id: 'usr-stud-01',
    name: 'Lucas Mendes Prado (Aluno)',
    email: 'lucas.prado@aluno.instituto.edu.br',
    role: 'student',
    title: 'Aluno de Graduação / Bolsista PIBIC',
    department: 'Engenharia de Software',
    matricula: '2024-ENG-034',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    permissions: ROLE_PERMISSIONS.student,
  },
];


export const SEED_LABS: Laboratory[] = [
  {
    id: 'lab-01',
    name: 'Laboratório de Redes e Infraestrutura',
    code: 'LAB-RED-101',
    capacity: 32,
    computersCount: 30,
    location: 'Bloco A — 1º Andar, Sala 102',
    status: 'available',
    installedSoftware: ['Wireshark', 'Packet Tracer', 'GNS3', 'Linux Ubuntu LTS', 'Docker Desktop'],
    description: 'Bancadas equipadas com switches gerenciáveis Cisco, patch panels e cabeamento estruturado.',
    equipmentCount: 14,
    supervisorName: 'Prof. Roberto Alencar',
    openTime: '07:30',
    closeTime: '22:00',
    tags: ['Redes', 'Cisco', 'Segurança', 'Linux'],
    currentActivity: 'Livre para agendamento',
  },
  {
    id: 'lab-02',
    name: 'Laboratório de Prototipagem & IoT',
    code: 'LAB-IOT-102',
    capacity: 24,
    computersCount: 12,
    location: 'Bloco B — Térreo, Sala 04',
    status: 'occupied',
    installedSoftware: ['Arduino IDE', 'KiCad', 'Autodesk Fusion 360', 'VS Code', 'Python 3.12'],
    description: 'Espaço maker com bancadas antiestáticas (ESD), estações de solda, fontes digitais e osciloscópios.',
    equipmentCount: 22,
    supervisorName: 'Ana Silva Santos',
    openTime: '08:00',
    closeTime: '21:30',
    tags: ['Maker', 'Arduino', 'Soldagem', 'Hardware'],
    currentOccupant: 'Prof. Roberto Alencar',
    currentActivity: 'Aula Prática: Microcontroladores ESP32',
  },
  {
    id: 'lab-03',
    name: 'Laboratório de IA & Computação de Alto Desempenho',
    code: 'LAB-HPC-201',
    capacity: 28,
    computersCount: 28,
    location: 'Bloco C — 2º Andar, Sala 205',
    status: 'available',
    installedSoftware: ['PyTorch', 'TensorFlow', 'CUDA Toolkit 12', 'JupyterLab', 'MATLAB 2025'],
    description: 'Workstations equipadas com GPUs dedicadas NVIDIA RTX 4080 e ambiente isolado com refrigeração de precisão.',
    equipmentCount: 8,
    supervisorName: 'Dr. Marcelo Valença',
    openTime: '08:00',
    closeTime: '22:30',
    tags: ['IA', 'Deep Learning', 'GPUs', 'HPC'],
    currentActivity: 'Livre para agendamento',
  },
  {
    id: 'lab-04',
    name: 'Laboratório de Realidade Estendida (VR/AR)',
    code: 'LAB-VR-202',
    capacity: 16,
    computersCount: 8,
    location: 'Bloco C — 2º Andar, Sala 208',
    status: 'maintenance',
    installedSoftware: ['Unity 6', 'Unreal Engine 5.5', 'Blender 4.3', 'Meta Quest Developer Hub'],
    description: 'Área com piso emborrachado e sensores infravermelhos para rastreamento de espaço de imersão total.',
    equipmentCount: 10,
    supervisorName: 'Ana Silva Santos',
    openTime: '09:00',
    closeTime: '20:00',
    tags: ['VR', 'AR', 'Jogos', 'Imersão'],
    currentActivity: 'Manutenção preventiva de sensores óticos',
  },
];

export const SEED_EQUIPMENT: Equipment[] = [
  {
    id: 'eq-01',
    name: 'Osciloscópio Digital Tektronix TBS1052B-EDU',
    tag: 'PAT-0042',
    category: 'osciloscopio',
    brand: 'Tektronix',
    model: 'TBS1052B-EDU',
    serialNumber: 'C014299',
    status: 'available',
    location: 'Armário A2 — Gaveta 1',
    labId: 'lab-02',
    labName: 'Laboratório de Prototipagem & IoT',
    specifications: {
      'Largura de Banda': '50 MHz',
      Canais: '2 Canais analógicos',
      Amostragem: '1 GS/s',
      Tela: '7 polegadas WVGA',
    },
    accessories: ['Cabo de força ABNT', '2x Pontas de prova 10x/1x', 'Cabo USB-B', 'Manual impresso'],
  },
  {
    id: 'eq-02',
    name: 'Kit Robótica & Prototipagem Raspberry Pi 5 (8GB)',
    tag: 'PAT-0108',
    category: 'prototipagem',
    brand: 'Raspberry Pi Foundation',
    model: 'Pi 5 Developer Bundle',
    serialNumber: 'RPI5-9831',
    status: 'in_use',
    location: 'Balcão de Empréstimo',
    labId: 'lab-02',
    labName: 'Laboratório de Prototipagem & IoT',
    currentUserId: 'usr-stud-01',
    currentUserName: 'Lucas Mendes Prado',
    specifications: {
      Processador: 'Quad-core Arm Cortex-A76 2.4GHz',
      RAM: '8GB LPDDR4X',
      Armazenamento: 'MicroSD 128GB SanDisk Extreme',
      Conexões: 'PCIe 2.0, Gigabit Ethernet, 2x USB 3.0',
    },
    accessories: ['Fonte Oficial USB-C 27W', 'Cooler Ativo Oficial', 'Case Acrílico Protetor', 'MicroSD 128GB'],
  },
  {
    id: 'eq-03',
    name: 'Óculos de Realidade Virtual Meta Quest 3 (512GB)',
    tag: 'PAT-0219',
    category: 'vr_ar',
    brand: 'Meta',
    model: 'Quest 3 Pro-Lab',
    serialNumber: 'MQ3-44109',
    status: 'available',
    location: 'Armário VR — Prateleira Central',
    labId: 'lab-04',
    labName: 'Laboratório de Realidade Estendida (VR/AR)',
    specifications: {
      Display: '4K+ Infinite Display (2064x2208)',
      PassThrough: 'Color Passthrough de alta resolução',
      Áudio: 'Áudio espacial 3D integrado',
    },
    accessories: ['2x Controladores Touch Plus', 'Cabo Link USB-C 5m', 'Almofada de silicone facial', 'Carregador 18W'],
  },
  {
    id: 'eq-04',
    name: 'Estação de Solda e Retrabalho SMD Weller WTHA1',
    tag: 'PAT-0312',
    category: 'prototipagem',
    brand: 'Weller',
    model: 'WTHA1 Hot Air Station',
    serialNumber: 'WEL-55102',
    status: 'available',
    location: 'Bancada ESD #03',
    labId: 'lab-02',
    labName: 'Laboratório de Prototipagem & IoT',
    specifications: {
      Potência: '900W',
      Temperatura: '50°C a 600°C',
      Vazão: 'Até 100 l/min',
    },
    accessories: ['Bico angular 4mm', 'Bico difusor 10mm', 'Suporte articulado de bocal', 'Cabo de aterramento'],
    requiresSpecialTraining: true,
  },
  {
    id: 'eq-05',
    name: 'Servidor Portátil de IA NVIDIA Jetson AGX Orin (64GB)',
    tag: 'PAT-0455',
    category: 'computacao',
    brand: 'NVIDIA',
    model: 'Jetson AGX Orin Developer Kit',
    serialNumber: 'NV-AGX-8812',
    status: 'reserved',
    location: 'Rack Seguro HPC — Sala 205',
    labId: 'lab-03',
    labName: 'Laboratório de IA & HPC',
    specifications: {
      Desempenho: '275 TOPS',
      GPU: 'NVIDIA Ampere com 2048 núcleos + 64 Tensor Cores',
      RAM: '64GB 256-bit LPDDR5',
    },
    accessories: ['Fonte de alimentação 19V', 'Módulo Wi-Fi/BT com antenas', 'Cabo USB-C host'],
  },
  {
    id: 'eq-06',
    name: 'Impressora 3D de Alta Velocidade Creality K1 Max',
    tag: 'PAT-0511',
    category: 'impressao_3d',
    brand: 'Creality',
    model: 'K1 Max AI Camera',
    serialNumber: 'CR-K1-7782',
    status: 'maintenance',
    location: 'Espaço Maker — Bancada 01',
    labId: 'lab-02',
    labName: 'Laboratório de Prototipagem & IoT',
    specifications: {
      'Volume de Impressão': '300 x 300 x 300 mm',
      Velocidade: 'Até 600 mm/s',
      Extrusor: 'All-metal direct drive',
    },
    accessories: ['Placa flexível PEI', 'Kit de bicos reserva 0.4mm', 'Alicate de corte', 'Espátula metálica'],
    notes: 'Aguardando substituição do termistor do bico extrusor.',
  },
  {
    id: 'eq-07',
    name: 'Câmera Termográfica Flir One Pro USB-C',
    tag: 'PAT-0604',
    category: 'audiovisual',
    brand: 'FLIR Systems',
    model: 'One Pro Gen 3',
    serialNumber: 'FLIR-9021',
    status: 'available',
    location: 'Maleta de Instrumentação A',
    specifications: {
      'Resolução Térmica': '160 x 120 pixels',
      Faixa: '-20°C a 400°C',
      Tecnologia: 'FLIR MSX (Realce dinâmico multiespectral)',
    },
    accessories: ['Estojo protetor antichoque', 'Cabo carregador USB-C', 'Alça de segurança'],
  },
  {
    id: 'eq-08',
    name: 'Analisador Lógico USB Saleae Logic Pro 16',
    tag: 'PAT-0770',
    category: 'redes',
    brand: 'Saleae',
    model: 'Logic Pro 16 USB 3.0',
    serialNumber: 'SAL-16-339',
    status: 'available',
    location: 'Armário A1 — Prateleira 2',
    labId: 'lab-01',
    labName: 'Laboratório de Redes e Infraestrutura',
    specifications: {
      Canais: '16 digitais / analógicos',
      Amostragem: '500 MS/s digital, 50 MS/s analógico',
      Protocolos: 'Decodificação de SPI, I2C, UART, CAN, USB',
    },
    accessories: ['16x Cabos fly wire com garras micro', 'Cabo USB 3.0 blindado', 'Estojo emborrachado'],
  },
];

const TODAY = new Date().toISOString().split('T')[0];

export const SEED_RESERVATIONS: Reservation[] = [
  {
    id: 'res-01',
    title: 'Aula Teórica e Prática: Redes de Alta Disponibilidade',
    type: 'lab',
    resourceId: 'lab-01',
    resourceName: 'Laboratório de Redes e Infraestrutura',
    resourceCodeOrTag: 'LAB-RED-101',
    userId: 'usr-teach-01',
    userName: 'Prof. Roberto Alencar',
    userRole: 'teacher',
    userDepartment: 'Departamento de Computação',
    date: TODAY,
    startTime: '14:00',
    endTime: '17:30',
    purpose: 'Configuração de topologias com OSPF e BGP em roteadores físicos.',
    attendeesCount: 28,
    status: 'confirmed',
    isRecurring: false,
    createdAt: '2026-09-01T10:00:00Z',
    approvedBy: 'Dr. Marcelo Valença',
    approvedAt: '2026-09-01T11:30:00Z',
  },
  {
    id: 'res-02',
    title: 'Projeto Final: Sensoriamento com ESP32',
    type: 'lab',
    resourceId: 'lab-02',
    resourceName: 'Laboratório de Prototipagem & IoT',
    resourceCodeOrTag: 'LAB-IOT-102',
    userId: 'usr-teach-01',
    userName: 'Prof. Roberto Alencar',
    userRole: 'teacher',
    userDepartment: 'Departamento de Computação',
    date: TODAY,
    startTime: '08:00',
    endTime: '11:45',
    purpose: 'Soldagem e teste de bancada dos protótipos de telemetria.',
    attendeesCount: 20,
    status: 'confirmed',
    isRecurring: true,
    seriesId: 'series-iot-2026',
    recurrenceRule: {
      frequency: 'weekly',
      daysOfWeek: [new Date().getDay()],
      startDate: TODAY,
      endDate: '2026-12-15',
      totalOccurrences: 14,
    },
    createdAt: '2026-08-25T09:00:00Z',
    approvedBy: 'Dr. Marcelo Valença',
    approvedAt: '2026-08-25T09:15:00Z',
  },
  {
    id: 'res-03',
    title: 'Treinamento de Modelo com Visão Computacional',
    type: 'equipment',
    resourceId: 'eq-05',
    resourceName: 'Servidor Portátil de IA NVIDIA Jetson AGX Orin',
    resourceCodeOrTag: 'PAT-0455',
    userId: 'usr-admin-01',
    userName: 'Dr. Marcelo Valença',
    userRole: 'admin',
    date: TODAY,
    startTime: '13:00',
    endTime: '18:00',
    purpose: 'Benchmark e inferência com modelos YOLOv10 para automação industrial.',
    status: 'confirmed',
    isRecurring: false,
    createdAt: '2026-09-02T08:00:00Z',
  },
];

export const SEED_WAITLIST: WaitlistEntry[] = [
  {
    id: 'wait-01',
    resourceType: 'lab',
    resourceId: 'lab-01',
    resourceName: 'Laboratório de Redes e Infraestrutura',
    userId: 'usr-stud-01',
    userName: 'Lucas Mendes Prado',
    userRole: 'student',
    date: TODAY,
    startTime: '14:00',
    endTime: '17:30',
    purpose: 'Realizar testes do Trabalho de Graduação na bancada Cisco',
    priorityScore: 55,
    status: 'waiting',
    createdAt: '2026-09-01T14:30:00Z',
  },
  {
    id: 'wait-02',
    resourceType: 'equipment',
    resourceId: 'eq-05',
    resourceName: 'Servidor Portátil de IA NVIDIA Jetson AGX Orin',
    userId: 'usr-teach-01',
    userName: 'Prof. Roberto Alencar',
    userRole: 'teacher',
    date: TODAY,
    startTime: '13:00',
    endTime: '18:00',
    purpose: 'Validação de algoritmo de navegação autônoma',
    priorityScore: 110,
    status: 'waiting',
    createdAt: '2026-09-02T08:45:00Z',
  },
];

export const SEED_CUSTODY: CustodyRecord[] = [
  {
    id: 'cust-01',
    equipmentId: 'eq-02',
    equipmentName: 'Kit Robótica & Prototipagem Raspberry Pi 5 (8GB)',
    equipmentTag: 'PAT-0108',
    userId: 'usr-stud-01',
    userName: 'Lucas Mendes Prado',
    userRole: 'student',
    userEmail: 'lucas.prado@aluno.instituto.edu.br',
    technicianId: 'usr-tech-01',
    technicianName: 'Ana Silva Santos',
    checkoutDate: '2026-09-01T10:15:00Z',
    expectedReturnDate: `${TODAY}T18:00:00Z`,
    status: 'active',
    accessoriesChecked: [
      'Fonte Oficial USB-C 27W',
      'Cooler Ativo Oficial',
      'Case Acrílico Protetor',
      'MicroSD 128GB',
    ],
    initialConditionNotes: 'Aparelho em excelente estado. Sem riscos visíveis. Boot testado com sucesso.',
    signatureSimulated: true,
    hasDamage: false,
  },
  {
    id: 'cust-02',
    equipmentId: 'eq-07',
    equipmentName: 'Câmera Termográfica Flir One Pro USB-C',
    equipmentTag: 'PAT-0604',
    userId: 'usr-teach-01',
    userName: 'Prof. Roberto Alencar',
    userRole: 'teacher',
    userEmail: 'roberto.alencar@instituto.edu.br',
    technicianId: 'usr-tech-01',
    technicianName: 'Ana Silva Santos',
    checkoutDate: '2026-08-28T09:00:00Z',
    expectedReturnDate: '2026-08-30T17:00:00Z',
    actualReturnDate: '2026-08-30T16:20:00Z',
    status: 'returned',
    accessoriesChecked: ['Estojo protetor antichoque', 'Cabo carregador USB-C', 'Alça de segurança'],
    initialConditionNotes: 'Completa e com carga total.',
    returnConditionNotes: 'Devolvida sem nenhuma avaria e com todos os cabos.',
    signatureSimulated: true,
    hasDamage: false,
  },
];

export const SEED_MAINTENANCE: MaintenanceOrder[] = [
  {
    id: 'maint-01',
    orderNumber: 'OS-2026-004',
    equipmentId: 'eq-06',
    equipmentName: 'Impressora 3D de Alta Velocidade Creality K1 Max',
    equipmentTag: 'PAT-0511',
    reportedBy: 'Ana Silva Santos',
    reportedAt: '2026-08-29T14:20:00Z',
    assignedTechnicianId: 'usr-tech-01',
    assignedTechnicianName: 'Ana Silva Santos',
    priority: 'high',
    status: 'waiting_parts',
    problemDescription: 'Erro de leitura térmica no hotend durante aquecimento (código E05).',
    diagnosis: 'Termistor NTC 100k rompido internamente devido a estresse mecânico.',
    partsUsed: ['Termistor original Creality K1'],
    downtimeHours: 96,
  },
  {
    id: 'maint-02',
    orderNumber: 'OS-2026-002',
    equipmentId: 'eq-04',
    equipmentName: 'Estação de Solda e Retrabalho SMD Weller WTHA1',
    equipmentTag: 'PAT-0312',
    reportedBy: 'Prof. Roberto Alencar',
    reportedAt: '2026-08-15T09:30:00Z',
    assignedTechnicianId: 'usr-tech-01',
    assignedTechnicianName: 'Ana Silva Santos',
    priority: 'medium',
    status: 'resolved',
    problemDescription: 'Fluxo de ar oscilando em temperaturas superiores a 400°C.',
    diagnosis: 'Obstrução parcial de poeira no filtro de admissão traseiro.',
    resolutionNotes: 'Filtro higienizado e recalibração digital do sensor de fluxo de ar realizada.',
    resolvedAt: '2026-08-16T11:00:00Z',
    downtimeHours: 25,
  },
];

export const SEED_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-01',
    title: 'Reserva Confirmada',
    message: 'Sua reserva para o Laboratório de Redes foi confirmada pelo administrador.',
    type: 'success',
    read: false,
    createdAt: '2026-09-01T11:30:00Z',
    linkTab: 'reservations',
  },
  {
    id: 'notif-02',
    title: 'Aviso de Devolução Próxima',
    message: 'O Kit Raspberry Pi 5 (PAT-0108) deve ser devolvido até hoje às 18:00 no Balcão.',
    type: 'warning',
    read: false,
    createdAt: `${TODAY}T08:00:00Z`,
    linkTab: 'custody',
    actionRequired: true,
  },
  {
    id: 'notif-03',
    title: 'Chamado Técnico Aberto',
    message: 'Ordem de serviço OS-2026-004 aberta para a Impressora 3D K1 Max.',
    type: 'info',
    read: true,
    createdAt: '2026-08-29T14:20:00Z',
    linkTab: 'maintenance',
  },
];

export const SEED_AUDIT: AuditLogEntry[] = [
  {
    id: 'aud-01',
    timestamp: '2026-09-01T10:00:00Z',
    userId: 'usr-teach-01',
    userName: 'Prof. Roberto Alencar',
    userRole: 'teacher',
    action: 'RESERVATION_CREATED',
    details: 'Solicitou reserva para LAB-RED-101 no horário 14:00 - 17:30',
    entityType: 'reservation',
    entityId: 'res-01',
  },
  {
    id: 'aud-02',
    timestamp: '2026-09-01T11:30:00Z',
    userId: 'usr-admin-01',
    userName: 'Dr. Marcelo Valença',
    userRole: 'admin',
    action: 'RESERVATION_APPROVED',
    details: 'Aprovou formalmente a reserva res-01 para Prof. Roberto Alencar',
    entityType: 'reservation',
    entityId: 'res-01',
  },
  {
    id: 'aud-03',
    timestamp: '2026-09-01T10:15:00Z',
    userId: 'usr-tech-01',
    userName: 'Ana Silva Santos',
    userRole: 'technician',
    action: 'CUSTODY_CHECKOUT',
    details: 'Realizou retirada do Kit Raspberry Pi 5 (PAT-0108) para o aluno Lucas Mendes',
    entityType: 'custody',
    entityId: 'cust-01',
  },
  {
    id: 'aud-04',
    timestamp: '2026-09-02T08:00:00Z',
    userId: 'usr-admin-01',
    userName: 'Dr. Marcelo Valença',
    userRole: 'admin',
    action: 'AUTH_LOGIN',
    details: 'Iniciou sessão no sistema LabTech',
    entityType: 'system',
    entityId: 'session',
  },
];

export const SEED_SIMULATED_EMAILS: SimulatedEmailLog[] = [
  {
    id: 'mail-01',
    to: 'roberto.alencar@instituto.edu.br',
    recipientName: 'Prof. Roberto Alencar',
    subject: '[LabTech] Confirmação de Reserva — LAB-RED-101',
    body: 'Prezado(a) Prof. Roberto Alencar, sua solicitação de reserva para o Laboratório de Redes e Infraestrutura (14:00 às 17:30) foi confirmada com sucesso.',
    sentAt: '2026-09-01T11:30:00Z',
    context: 'reservation_created',
  },
  {
    id: 'mail-02',
    to: 'lucas.prado@aluno.instituto.edu.br',
    recipientName: 'Lucas Mendes Prado',
    subject: '[LabTech Alerta] Lembrete de Devolução — Kit Raspberry Pi 5',
    body: 'Olá Lucas, lembramos que o equipamento PAT-0108 deve ser devolvido até hoje às 18:00 no Balcão de Custódia. O atraso acarretará no bloqueio temporário de novas reservas.',
    sentAt: '2026-09-03T08:00:00Z',
    context: 'custody_overdue',
  },
];

